Fixes 4 mr
SyneRBI/SIRF-Exercises pull request #138
Opened 2021-06-25 21:18 UTC by ckolbPTB

some final fixes

2021-06-25 21:33 UTC, KrisThielemans requested changes

2021-06-25 21:33 UTC, KrisThielemans commented on notebooks/MR/c_coil_combination.ipynb
> +    "# Demonstration of MR reconstruction with CCP PET-MR Software\n",
```suggestion
    "# Demonstration of MR reconstruction with SIRF\n",
```

2021-06-25 21:33 UTC, KrisThielemans commented on notebooks/MR/c_coil_combination.ipynb
> +    "Updated 10th of April 2019  \n",
might want to update this

2021-06-25 21:33 UTC, KrisThielemans commented on notebooks/MR/c_coil_combination.ipynb
> +    "CCP PETMR Synergistic Image Reconstruction Framework (SIRF).  \n",
```suggestion
    "CCP SyneRBI Synergistic Image Reconstruction Framework (SIRF).  \n",
```

2021-06-25 21:33 UTC, KrisThielemans commented on notebooks/MR/c_coil_combination.ipynb
> +    "Copyright 2015 - 2017 Physikalisch-Technische Bundesanstalt.  \n",
```suggestion
    "Copyright 2015 - 2017, 2021 Physikalisch-Technische Bundesanstalt.  \n",
```

2021-06-26 17:42 UTC, ckolbPTB commented
I hope I did not miss any...

2021-06-26 18:18 UTC, merged