Some more tidying, and using wget for the binaries
SyneRBI/SIRF-Exercises pull request #174
Opened 2022-05-25 15:52 UTC by Imraj-Singh

Using wget from a personal onedrive file instead of storing it within the repository.

2022-05-25 15:59 UTC, DANAJK commented
We also have a Zenodo community for data where you could put items for download if you wish. (Suitable only for stable items and the items remain public forever.) In the Geometry notebooks, there is a get_nifti_data notebook that uses `curl` to access this:
```
# Setup the working directory for the notebook
import notebook_setup
from sirf_exercises import cd_to_working_dir
cd_to_working_dir('Geometry')

import os

# Cet data, unzip
# curl will download into the current directory

!curl -O https://zenodo.org/record/4940072/files/nifti.zip
!unzip nifti.zip
```

2022-05-25 16:25 UTC, KrisThielemans requested changes

2022-05-25 16:28 UTC, KrisThielemans commented
Relying on `wget` and `curl` command line utilities is generally dangerous as you don't know if they're installed. We use `curl` already (also in `download.sh`), it'll be on the VMs/docker etc, so I'd prefer that.

at some point, we have to replace this with Python download...

2022-05-25 20:10 UTC, Imraj-Singh commented on notebooks/Deep_Learning_PET/.gitattributes
> +*.torch binary
There are "built-in macro attribute(s)" from my understanding. It's in the "USING MACRO ATTRIBUTES" section. It's equivalent to the text and diff attributes so I though it was fine... I am happy to change, let me know

2022-05-25 20:12 UTC, Imraj-Singh commented
> Relying on `wget` and `curl` command line utilities is generally dangerous as you don't know if they're installed. We use `curl` already (also in `download.sh`), it'll be on the VMs/docker etc, so I'd prefer that.
> 
> at some point, we have to replace this with Python download...

I have added some checks to see if the files are downloaded if that helps my case?

2022-05-25 20:44 UTC, DANAJK commented
Provided it is clear in the code or comments where the data is located, and where to download it to, I think it is acceptable for people to do it themselves. So, for now it’s fine to provide a OneDrive URL.

I wouldn’t mess with that download_data script at this stage.

2022-05-25 21:46 UTC, KrisThielemans commented
> 

agreed!

But @Imraj-Singh please use `curl` unless you're 100% sure that `wget` is available on the 3 systems...

2022-05-25 23:04 UTC, Imraj-Singh commented
@DANAJK @KrisThielemans the wget is within one of the notebooks (the 4th), so from my understanding the download will be the same directory as the notebook. So the participant will see the model and results downloaded into the same directory as the notebook which goes onto use it.

@KrisThielemans by 3 systems do you mean windows, linux and mac, or the three servers in jupyter hub (I guess the three servers use different resources). Thanks! I can check this tomorrow rather quickly.

2022-05-26 10:39 UTC, KrisThielemans commented
@Imraj-Singh please just replace `wget` with `curl`. Less headache!
(3 systems: VM, docker, jupyterhub, and even if it's there, we probably don't guarantee it)

2022-05-26 10:58 UTC, KrisThielemans commented on notebooks/Deep_Learning_PET/.gitattributes
> +*.torch binary
please check. e.g.
 ```
~/devel/SIRF/data/examples/PET$ git check-attr -a Utahscat600k_ca_seg4.s
Utahscat600k_ca_seg4.s: diff: unset
Utahscat600k_ca_seg4.s: text: unset
```

2022-05-26 18:00 UTC, Imraj-Singh commented on notebooks/Deep_Learning_PET/.gitattributes
> +*.torch binary
~/SIRF-Exercises/notebooks/Deep_Learning_PET$ git check-attr -a trained.torch
trained.torch: binary: set
trained.torch: diff: unset
trained.torch: merge: unset
trained.torch: text: unset

2022-05-26 18:04 UTC, Imraj-Singh commented
@KrisThielemans that's it changed to curl, was rather involved as wget hides the use of cookies and redirect where curl you have to specify. I guess this is living and learning...

2022-05-26 18:14 UTC, KrisThielemans commented on notebooks/Deep_Learning_PET/.gitattributes
> +*.torch binary
great

2022-05-26 18:18 UTC, KrisThielemans commented
Thanks!

Ready to merge?

2022-05-27 04:14 UTC, Imraj-Singh commented
yes please, the codacy changes seem rather trivial unless you'd like those fixed before merging?

2022-05-27 05:17 UTC, merged