DL notebook fixes
SyneRBI/SIRF-Exercises pull request #222
Opened 2024-04-16 09:14 UTC by Imraj-Singh

Dealing with a couple errors when running without GPU. One being `print(torch.cuda.get_device_name(0))` is called even when installed without cuda, the other `checkpoint = torch.load('trained.torch_model')` mapped to GPU.

Also removing requires_grad_() as per Georg's comment.

2024-04-16 16:58 UTC, KrisThielemans commented
Just ping me or @evgueni-ovtchinnikov when you want this to be merged.

2024-04-16 16:59 UTC, KrisThielemans commented
best to add a line to CHANGES.md

2024-04-23 09:45 UTC, Imraj-Singh commented
@KrisThielemans added a line to changes.md think it's fine to merge. They're very minor changes

2024-04-23 10:31 UTC, KrisThielemans commented on CHANGES.md
> +* small updates to DL notebooks
```suggestion
* small updates to DL notebooks [#222](https://github.com/SyneRBI/SIRF-Exercises/pull/222)
```

2024-04-23 10:31 UTC, KrisThielemans requested changes

2024-04-23 10:31 UTC, KrisThielemans commented on CHANGES.md
> +* small updates to DL notebooks
otherwise not too informative :-/

2024-05-16 00:35 UTC, merged