Refactor download path
SyneRBI/SIRF-Exercises pull request #82
Opened 2021-05-18 10:00 UTC by ashgillman

Fix #22 

NB: This was my original proposed solution as I'd already used the home directory rather than the repo directory. This will need to change.

Also, haven't fixed for the Brainweb data

2021-05-18 10:21 UTC, paskino commented
I like the unification of the download scripts. But I'm not sure the rest works as we are discussing in #22

2021-05-18 10:27 UTC, ashgillman commented
> I'm not sure the rest works as we are discussing in #22

I agree, I'd written half before the most recent comments. I'll change these once we've settled.

2021-05-18 11:08 UTC, ashgillman commented on notebooks/PET/reconstruct_measured_data.ipynb
> +    "data_path = os.path.join('..', '..', 'data')\n",
I don't like this - if the use runs the cell twice they'll get an error because we're using a relative directory. But Notebooks don't have an option to use `__file__` so I can't see how to define this in a way without being relative to the notebook directory

2021-05-18 11:10 UTC, ashgillman commented
Hmm, this doesn't run... `reconstruct_measured_data.ipynb` expects a `norm.n.hdr` and other files that aren't in the downloads. I can't see anywhere these files are created..?

2021-05-18 13:12 UTC, paskino commented on notebooks/PET/reconstruct_measured_data.ipynb
> +    "data_path = os.path.join('..', '..', 'data')\n",
I think the latest discussion in #22 means that we will create a `common.py` file in each subdirectory where the downloaded data is required. Then we have access to `__file__` and the value of the data location.

2021-05-18 13:20 UTC, ashgillman commented on notebooks/PET/reconstruct_measured_data.ipynb
> +    "data_path = os.path.join('..', '..', 'data')\n",
common + sys.path.append ?

2021-05-18 14:55 UTC, paskino commented on notebooks/PET/reconstruct_measured_data.ipynb
> +    "data_path = os.path.join('..', '..', 'data')\n",
I think `common.py` should be sufficient?

2021-05-18 16:31 UTC, paskino commented
I'm stumbling upon the same problem. Shouldn't the download script handle this?

2021-05-19 02:54 UTC, ashgillman commented
I don't know when the conversion was done previously for this notebook - but I think its quite nice to show the user that you need to run convertSiemensInterfileToSTIR on measured scanner data, so I've added the cell in here.

Certainly, this script isn't referenced elsewhere in this repo - so I'm at a loss as to how this notebook ran last workshop?

2021-05-19 04:52 UTC, ashgillman commented
@paskino - Ignore my comments on your PR to my PR, I didn't see what you were doing.

I've incorporated here.

I still think its a bit ugly, but if we want to be able to declare a location when we run download_data.sh and have that permanent there's no clear alternative :+1:

2021-05-19 05:42 UTC, ashgillman commented
Okay, I think this addresses everything now?

2021-05-19 06:42 UTC, KrisThielemans requested changes

2021-05-19 06:42 UTC, KrisThielemans commented on notebooks/PET/reconstruct_measured_data.ipynb
> +    "print('num prompts in this segments: %d' % acq_array.sum())\n",
why do you say in "this segment"? Maybe you are talking about the first 600s, but "segment" terminology is confusing. Please remove

2021-05-19 06:42 UTC, KrisThielemans commented on scripts/download_MR_data.sh
>  # if no argument is used, the destination directory will be set to ~/data
this needs changing i guess. Best to refer to download_data.sh for default location

2021-05-19 06:42 UTC, KrisThielemans commented on scripts/download_MR_data.sh
> +# Copyright (C) 2018-2021 University College London
nothing from us remains, so remove us and UCL

2021-05-19 06:42 UTC, KrisThielemans commented on scripts/download_MR_data_old_notebooks.sh
>  # if no argument is used, the destination directory will be set to ~/data
this needs changing i guess.

2021-05-19 06:42 UTC, KrisThielemans commented on scripts/download_MR_data_old_notebooks.sh
> +# Copyright (C) 2018-2021 University College London
as above

2021-05-19 06:42 UTC, KrisThielemans commented on scripts/download_PET_data.sh
> +# Author: Kris Thielemans, Ashley Gillman
remove me and UCL

2021-05-19 06:42 UTC, KrisThielemans commented on scripts/download_PET_data.sh
> +# the destination directory will be set to ~/.sirf-exercises/data/PET.
Best to refer to download_data.sh for default location

2021-05-19 06:42 UTC, KrisThielemans commented on scripts/download_data.sh
> +# A sript to download all data for the SIRF-Exercises course
typo `script`

2021-05-19 06:42 UTC, KrisThielemans commented on scripts/download_data.sh
> +    echo "A sript to download all data for the SIRF-Exercises course"
typo

2021-05-19 06:42 UTC, KrisThielemans commented on scripts/download_data.sh
> +    echo "  DEST_DIR  Optional desination directory."
```suggestion
    echo "  DEST_DIR  Optional destination directory."
```

2021-05-19 06:42 UTC, KrisThielemans commented on scripts/download_data.sh
> +DATA_PATH=${DATA_PATH:-${REPO_DIR}/data}
ideally add some comments on what this does. I find the usage of `OPTIND` so far below the `getopts` a bit confusing by the way. Create a variable higher up?

2021-05-19 06:42 UTC, KrisThielemans commented on scripts/download_data.sh
> +    echo "            with a default value of SIRF_EXERCISES_PATH=\"~/.sirf-exercises\""
I don't think this fits the code below (which makes me happy...)

2021-05-19 06:42 UTC, KrisThielemans commented on scripts/download_data.sh
> +# create the common.py files in each notebook directory
inaccurate filename

2021-05-19 06:42 UTC, KrisThielemans commented on scripts/download_data.sh
> +    cat <<-EOF >${REPO_DIR}/notebooks/$d/data_path.py
I see no value in having the `cat <<EOF` trick twice. Possibly `echo` works the 2nd time. Otherwise I'd get rid of the first.

2021-05-19 06:44 UTC, KrisThielemans commented
> I don't know when the conversion was done previously for this notebook - but I think its quite nice to show the user that you need to run convertSiemensInterfileToSTIR on measured scanner data, so I've added the cell in here.
> 
> Certainly, this script isn't referenced elsewhere in this repo - so I'm at a loss as to how this notebook ran last workshop?

agreed it's good to add it here. It might be possible that it was run by Ben on the data before upload, but not sure.

Did you test using this mu-map?

2021-05-19 12:12 UTC, paskino commented on scripts/download_data.sh
> +    cat <<-EOF >${REPO_DIR}/notebooks/$d/data_path.py
I have no clue. I found that solution on [SO](https://stackoverflow.com/questions/7875540/how-to-write-multiple-line-string-using-bash-with-variables#7875614).

2021-05-19 12:16 UTC, paskino commented on notebooks/Synergistic/BrainWeb-single_slice_motion.ipynb
> +    "data_path = path.join(data_path, 'Synergistic', 'brainweb_single_slice')\n",
are you sure that this `data_path` should be the `notebooks_data_path`?

2021-05-19 12:18 UTC, paskino commented on scripts/download_data.sh
> +    cat <<-EOF >${REPO_DIR}/notebooks/$d/data_path.py
I had user the term `exercises_data_path` to make clear that this path is relative to the real data that gets downloaded by the `download_data.sh` script in this repo. 

I think that removing `exercises_` makes this less clear.

2021-05-19 12:28 UTC, paskino requested changes
I have 2 comments:

1. I think the only PET notebook requiring the notebook data is `reconstruc_measured_data.ipynb`. All the other ones use simulated data or brainweb which is not downloaded by the `download_data.sh` script
2. I had named the module containing the path for the downloaded data as `exercises_data_path` with the idea to be explicit in what that directory really was. Using just `data_path` isn't so clear:
```python
# I prefer
from exercises_data_path import data_path
# over
from data_path import data_path
```

2021-05-20 00:27 UTC, ashgillman commented on notebooks/PET/reconstruct_measured_data.ipynb
> +    "print('num prompts in this segments: %d' % acq_array.sum())\n",
Whoops, thanks. I originally thought idx 0 was segment but actually its ToF bin of course.

NB: I was a little surprised here and had a look into the documentation. Its not clear there how STIR.AcquisitionData.as_array handles() segments.

NBB: The reason I added this originally is that `lm2sino` was returning an empty array. I fixed by updating STIR and SIRF, but I was only about a month old. Couldn't see any relevant PRs in the last few months. Strange!

2021-05-20 00:29 UTC, ashgillman commented on scripts/download_MR_data.sh
> +# Copyright (C) 2018-2021 University College London
Should these be marked as deprecated? I thought it nice to keep them here in case any scripts use them for the time being.

2021-05-20 00:36 UTC, ashgillman commented on scripts/download_data.sh
> +    echo "            with a default value of SIRF_EXERCISES_PATH=\"~/.sirf-exercises\""
:laughing: I'm a bit sad - I was pretty happy with that :stuck_out_tongue:

2021-05-20 00:40 UTC, ashgillman commented on notebooks/Synergistic/BrainWeb-single_slice_motion.ipynb
> +    "data_path = path.join(data_path, 'Synergistic', 'brainweb_single_slice')\n",
Well this is used as a work directory - so it could be done in many places. But certainly examples_data_path is bad, because this was putting brainweb data in there. I think this location is consistent with the other's usage

2021-05-20 00:49 UTC, ashgillman commented
> 1. I think the only PET notebook requiring the notebook data is reconstruc_measured_data.ipynb. All the other ones use simulated data or brainweb which is not downloaded by the download_data.sh script

Yes - does something need to change?

> 2. I had named the module containing the path for the downloaded data as exercises_data_path with the idea to be explicit in what that directory really was. Using just data_path isn't so clear:

I agree :+1:

2021-05-20 06:07 UTC, ashgillman commented
> > I don't know when the conversion was done previously for this notebook - but I think its quite nice to show the user that you need to run convertSiemensInterfileToSTIR on measured scanner data, so I've added the cell in here.
> > Certainly, this script isn't referenced elsewhere in this repo - so I'm at a loss as to how this notebook ran last workshop?
> 
> agreed it's good to add it here. It might be possible that it was run by Ben on the data before upload, but not sure.

I thought so also, but it's not listed on the Zenodo. So long as you're happy with this solution.

> Did you test using this mu-map?

I have tested that `reconstruct_measured_data.ipynb` runs to completion.

My Gadgetron is currently not working, so I have only tested the 4 affected MR notebooks up to when they load the acquisition data, I haven't run the reconstructions.

I have not tested any old notebooks - as I can't see that any actually use the downloaded data. Especially not the meas*.dat files, maybe they can be removed?

2021-05-20 06:14 UTC, ashgillman commented
I think all comments above are addressed

2021-05-20 06:40 UTC, KrisThielemans requested changes
a few typos and remaining `data_path`

2021-05-20 06:40 UTC, KrisThielemans commented on notebooks/Synergistic/BrainWeb-single_slice_motion.ipynb
> +    "from data_path import data_path"
presumably `exercises_data_path`? Also below.

2021-05-20 06:40 UTC, KrisThielemans commented on notebooks/Synergistic/BrainWeb-single_slice_motion.ipynb
>      "from sirf.Utilities import examples_data_path\n",
could cut this

2021-05-20 06:40 UTC, KrisThielemans commented on notebooks/Synergistic/BrainWeb.ipynb
> +    "from data_path import data_path"
`exercises_data_path`

2021-05-20 06:40 UTC, KrisThielemans commented on notebooks/Synergistic/BrainWeb.ipynb
> +    "data_path = path.join(data_path, 'Synergistic', 'brainweb')\n",
exercises_data_path

2021-05-20 06:40 UTC, KrisThielemans commented on notebooks/Synergistic/HKEM_reconstruction.ipynb
> +    "from data_path import data_path\n",
exercises_data_path

2021-05-20 06:40 UTC, KrisThielemans commented on notebooks/Synergistic/HKEM_reconstruction.ipynb
> +    "os.chdir(os.path.join(data_path, 'Synergistic'))\n",
exercises_data_path

2021-05-20 06:40 UTC, KrisThielemans commented on notebooks/Synergistic/Solutions/Dual_PET_Answer-noMotion.ipynb
> +    "from data_path import data_path\n",
exercises_data_path

2021-05-20 06:40 UTC, KrisThielemans commented on notebooks/Synergistic/Solutions/Dual_PET_Answer-noMotion.ipynb
> +    "os.chdir(os.path.join(data_path, 'Synergistic'))\n",
exercises_data_path

2021-05-20 06:40 UTC, KrisThielemans commented on notebooks/Synergistic/Solutions/Dual_PET_Answer-wMotion.ipynb
> +    "from data_path import data_path\n",
exercises_data_path

2021-05-20 06:40 UTC, KrisThielemans commented on notebooks/Synergistic/Solutions/Dual_PET_Answer-wMotion.ipynb
> +    "os.chdir(os.path.join(data_path, 'Synergistic'))\n",
exercises_data_path

2021-05-20 06:40 UTC, KrisThielemans commented on notebooks/Synergistic/de_Pierro_MAPEM.ipynb
> +    "from data_path import data_path\n",
exercises_data_path

2021-05-20 06:40 UTC, KrisThielemans commented on notebooks/Synergistic/de_Pierro_MAPEM.ipynb
> +    "os.chdir(os.path.join(data_path, 'Synergistic'))\n",
exercises_data_path

2021-05-20 06:40 UTC, KrisThielemans commented on scripts/download_MR_data_old_notebooks.sh
> +# A sript to download data for the MR/Old_notebooks part of the SIRF-Exercises course
script

2021-05-20 06:40 UTC, KrisThielemans commented on scripts/download_MR_data.sh
> +# A sript to download data for the MR part of the SIRF-Exercises course
script

2021-05-20 06:44 UTC, KrisThielemans commented
> have not tested any old notebooks - as I can't see that any actually use the downloaded data. Especially not the meas*.dat files, maybe they can be removed?

old MR notebooks? I guess that's a question for @DANAJK and @ckolbPTB. Definitely out-of-scope for this PR

2021-05-20 08:23 UTC, paskino commented on notebooks/Synergistic/BrainWeb-single_slice_motion.ipynb
> +    "from data_path import data_path"
I don't think it's required here

2021-05-20 08:24 UTC, paskino commented on notebooks/Synergistic/BrainWeb.ipynb
> +    "data_path = path.join(data_path, 'Synergistic', 'brainweb')\n",
I think all these don't use the data that has been downloaded with `download_data.sh`. Should we use `exercises_data_path`?

2021-05-20 08:25 UTC, paskino commented
@ashgillman I have tested the MR notebooks. I haven't tested the `old` ones though.

2021-05-20 09:44 UTC, merged