Gradient descent
SyneRBI/SIRF-Exercises pull request #85
Opened 2021-05-21 08:45 UTC by ckolbPTB

I created a notebook which does gradient descent for MR, PET and CT. Somewhere towards the end of the notebook you find the parameter `curr_modality` which can be set to either `mr`, `pet` or `ct` in order to use the different modalities. 

The step-size `tau` has to be adapted for each modality. Values which I found to work ok, where 0.03 for `mr`, 0.3 for `pet` and 0.1 for `ct`. Would be great if somebody could try it.

2021-06-02 16:00 UTC, evgueni-ovtchinnikov requested changes
Some suggestions made for moving from `as_array` + `fill` + `numpy` algebra to SIRF algebra.

2021-06-02 16:22 UTC, KrisThielemans commented
> Some suggestions made for moving from `as_array` + `fill` + `numpy` algebra to SIRF algebra.

great. I guess it was based on older examples/notebooks? Maybe the PET notebook still does that (even though the SIRF example doesn't)

2021-06-02 16:26 UTC, KrisThielemans commented on notebooks/Synergistic/gradient_descent_mr_pet_ct.ipynb
> +    "    curr_image_estimate.fill(curr_image_estimate_array)\n",
The `maximum` trick is a bit hard to understand. What about putting that in `make_positive` function, such that this code is cleaner?

This is therefore actually constrained gradient descent. I believe the CT guys don't do that (although they could). @epapoutsellis , @paskino?

The comment text seems inconsistent at the moment. I guess it would have to see "In PET or CT, we have to ensure that..."

2021-06-02 16:27 UTC, KrisThielemans commented on notebooks/Synergistic/gradient_descent_mr_pet_ct.ipynb
> +    "        plot_2d_image([2,2,i+1], image_iteration[curr_it,centre_slice,:,:], 'It '+str(curr_it), cmap=\"viridis\")\n",
needs `abs`? (I didn't check)

2021-06-02 16:52 UTC, evgueni-ovtchinnikov commented on notebooks/Synergistic/gradient_descent_mr_pet_ct.ipynb
> +    "        plot_2d_image([2,2,i+1], image_iteration[curr_it,centre_slice,:,:], 'It '+str(curr_it), cmap=\"viridis\")\n",
see previous comment where `image` is defined

2021-06-08 12:49 UTC, ckolbPTB commented
@evgueni-ovtchinnikov Thank you very much for the suggestions to make it more object orientated rather than using numpy arrays. I made all the ammendments except for the check if the data is complex. Here I had to leave the old check on the numpy array, because the CT data does not have the method is_complex().

2021-06-08 12:58 UTC, KrisThielemans commented
great. I haven't checked the updated version yet, but what about making this a bit less "automatic" and let people do it by hand

```
if not image_data.as_array().dtype in [numpy.complex, numpy.complex64]:
```
->
```
if is_MRI:
```
and have a cell above it setting `is_MRI` and tell them what to set it.

I think it's less cryptic for an introductory notebook.

2021-06-08 20:40 UTC, ckolbPTB commented
I added a check based on the methodology which is select by the user.

2021-06-08 20:46 UTC, KrisThielemans commented
ready to merge? (we can fine-tune later if need be, but this way it's easier for people to see what it here)

2021-06-08 21:44 UTC, KrisThielemans approved these changes

2021-06-09 00:32 UTC, ashgillman reviewed
Looks good, I wonder if I can replicate with the PyTorch GD

2021-06-09 00:32 UTC, ashgillman commented on notebooks/Synergistic/gradient_descent_mr_pet_ct.ipynb
> +    "Copyright 2015 - 2017 Rutherford Appleton Laboratory STFC.  \n",
```suggestion
    "Copyright 2021 Rutherford Appleton Laboratory STFC.  \n",
```

2021-06-09 00:32 UTC, ashgillman commented on notebooks/Synergistic/gradient_descent_mr_pet_ct.ipynb
> +    "Copyright 2015 - 2019 University College London.   \n",
```suggestion
```

2021-06-09 07:29 UTC, merged

2021-06-09 07:30 UTC, KrisThielemans commented on notebooks/Synergistic/gradient_descent_mr_pet_ct.ipynb
> +    "Copyright 2015 - 2017 Rutherford Appleton Laboratory STFC.  \n",
I've kept these. This file contains copies of code that was written ages ago, so they are appropriate.

2021-06-09 07:30 UTC, KrisThielemans commented on notebooks/Synergistic/gradient_descent_mr_pet_ct.ipynb
> +    "Copyright 2015 - 2019 University College London.   \n",
I've kept these. This file contains copies of code that was written ages ago, so they are appropriate.