Data path continued
SyneRBI/SIRF-Exercises pull request #94
Opened 2021-06-08 11:14 UTC by ashgillman

Progress on #89:

  - [x] Fix remaining PET Notebooks
  - [x] `chdir` is absolute so can be run multiple times
  - [x] `from sirf_exercises import exercises_data_path`
  - [x] `examples_data_path` -> `examples_data_path()`
  - [x] exercise_data_path.py flagged by git - this was because .gitingore is only for new files, not modified - now we don't modify a file but create
  - [ ] Separate working directories from data_directories

2021-06-08 11:16 UTC, ashgillman commented
Testing completed:

ran `./scripts/download_data.sh`

ran `./scripts/download_data.sh data`

ran `./scripts/download_data.sh data ~/tmp` after copying downloaded files to `~/tmp` - they are found correctly

ran all modified notebooks until the `cd` command and ensured it ran

2021-06-08 12:09 UTC, ashgillman commented
I've also tested the PET notebooks. MAPEM runs, but gives some funky results - I presume unrelated.

![image](https://user-images.githubusercontent.com/816777/121182142-23761680-c8a6-11eb-93af-9617a03825bc.png)

2021-06-08 12:16 UTC, ashgillman commented
To explain how this works:

- each Notebook dir has a `notebook_setup.py` which need to be imported, and which will set the sys.path to point to SIRF-Exercises/lib
- Under lib are the library directories. If we wanted, these could include plotting and other repeated functions
- download_data.sh now creates lib/sirf_exercises/data_path.py with the location
- `exercises_data_path()` looks for that file, and also checks an ENV var which could be useful in the future but currently never really would be used. If it can't find the path it raises an exception.

2021-06-08 13:48 UTC, KrisThielemans requested changes
looks good. I didn't try it but you did!

some interesting indentation choices going on? I guess we need a clangformat here as well :-) Just choose whatever was used before for now

2021-06-08 13:48 UTC, KrisThielemans commented on scripts/download_data.sh
> +echo $DOWNLOAD_DIR
```suggestion
echo Download location is \"${DOWNLOAD_DIR}\"
```

2021-06-08 13:48 UTC, KrisThielemans commented on scripts/download_data.sh
> +DOWNLOAD_DIR="$(readlink -f ${DOWNLOAD_DIR})"  # canonicalise
I don't think MacOS has `readlink`, https://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac
I'd cut it (unless we really need this?)

2021-06-08 13:48 UTC, KrisThielemans commented on scripts/download_data.sh
> +    mkdir -p ${DOWNLOAD_DIR}
you could replace this with 
```suggestion
    mkdir -p "${DOWNLOAD_DIR}"
```
to be safe for spaces. or with a few less characters `"$DOWNLOAD_DIR"`.

or leave it for another day

2021-06-08 13:50 UTC, KrisThielemans commented
also a codacy suggestion for quoting and spaces

2021-06-08 22:54 UTC, ashgillman commented on scripts/download_data.sh
> +echo $DOWNLOAD_DIR
Whoops, that slipped in

2021-06-09 06:37 UTC, KrisThielemans requested changes
quotes everywhere 😄 !

I think now in too many places, but fine. I spotted only one mistake but am hoping you ran it again to see if it works.

2021-06-09 06:37 UTC, KrisThielemans commented on scripts/download_data.sh
> +if ! [[ "$DO_PET" || "$DO_MR" || "$"DO_OLD ]]; then
```suggestion
if ! [[ $DO_PET || $DO_MR || $DO_OLD ]]; then
```
no quotes necessary as never any spaces? In any case, one quote pair was wrong

2021-06-09 07:25 UTC, ashgillman commented
Yes, I know I went overboard there... It was easier than checking line-by-line with Codeacy
I think it should still be valid

Huh, I did test.. I think that slipped through based on short-circuiting. I've tested with different flags a little more rigorously.
Although I also removed those particular line as it is now desirable to be able to run the script without downloading any data, if no flags are specified, if you wanted to just configure the path file.

I have no idea how to please Codeacy! If I put the function docstring to start after \``` it says Multi-line docstring summary should start at the second line (D212)" and if I put a newline it says "Multi-line docstring summary should start at the first line (D212)"!

2021-06-09 07:26 UTC, ashgillman commented
Hmm, it has conflicting rules!
https://stackoverflow.com/questions/45990301/pep257-d212-and-d213-conflicts

2021-06-09 07:29 UTC, ashgillman commented
I personally prefer

```
def some_func():
   """A docstring.

    more detail.
    """
    return
```

which would mean disabling D213

2021-06-09 07:32 UTC, KrisThielemans approved these changes

2021-06-09 07:32 UTC, KrisThielemans commented
> Hmm, it has conflicting rules!
> https://stackoverflow.com/questions/45990301/pep257-d212-and-d213-conflicts

yes. I think the idea is that we choose one to enforce style. anyway

2021-06-09 07:33 UTC, merged